# Generated by Django 4.2 on 2023-04-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_q', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationmodule',
            options={'ordering': ['number'], 'verbose_name': 'Образовательный модуль', 'verbose_name_plural': 'Образовательные модули'},
        ),
    ]
