# Generated by Django 4.2 on 2023-04-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_q', '0002_alter_educationmodule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmodule',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
